name: doc

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - package.json
      - index.d.ts
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Rebuild website
        run: |
          curl -fsS \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -H 'Content-type: application/json' \
          -H "Authorization: Bearer $GH_PAT_ORG" \
          -X POST \
          -d '{"event_type":"build"}' \
          https://api.github.com/repos/$GH_REPO/dispatches
        env:
          GH_PAT_ORG: ${{ secrets.GH_PAT_ORG }}
          GH_REPO: violentmonkey/violentmonkey-astro

      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 11
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 26
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Build docs
        run: |
          pnpm i
          pnpm build:docs
          pnpm build:docs --json docs/types.json

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: docs
          single-commit: true
